services:
  - type: web
    name: nearx-backend
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
